title: PEGARECRUITERS
description: Adding new job requirements
template:
  repo: pegarecruiters-template
  name: pegarecruiters
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
